// Code generated by "stringer -type ScmId"; DO NOT EDIT.

package eddnc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Sblackmarket-0]
	_ = x[Scommodity-1]
	_ = x[Sjournal-2]
	_ = x[Soutfitting-3]
	_ = x[Sshipyard-4]
}

const _ScmId_name = "SblackmarketScommoditySjournalSoutfittingSshipyard"

var _ScmId_index = [...]uint8{0, 12, 22, 30, 41, 50}

func (i ScmId) String() string {
	if i < 0 || i >= ScmId(len(_ScmId_index)-1) {
		return "ScmId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScmId_name[_ScmId_index[i]:_ScmId_index[i+1]]
}
