// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "fmt"
import "encoding/json"

type OutfittingV20JsonHeader struct {
	// Timestamp upon receipt at the gateway. If present, this property will be
	// overwritten by the gateway; submitters are not intended to populate this
	// property.
	GatewayTimestamp *string `json:"gatewayTimestamp,omitempty"`

	// SoftwareName corresponds to the JSON schema field "softwareName".
	SoftwareName string `json:"softwareName"`

	// SoftwareVersion corresponds to the JSON schema field "softwareVersion".
	SoftwareVersion string `json:"softwareVersion"`

	// UploaderID corresponds to the JSON schema field "uploaderID".
	UploaderID string `json:"uploaderID"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OutfittingV20JsonHeader) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["softwareName"]; !ok || v == nil {
		return fmt.Errorf("field softwareName: required")
	}
	if v, ok := raw["softwareVersion"]; !ok || v == nil {
		return fmt.Errorf("field softwareVersion: required")
	}
	if v, ok := raw["uploaderID"]; !ok || v == nil {
		return fmt.Errorf("field uploaderID: required")
	}
	type Plain OutfittingV20JsonHeader
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = OutfittingV20JsonHeader(plain)
	return nil
}

type OutfittingV20JsonMessage struct {
	// Whether the sending Cmdr has a Horizons pass.
	Horizons *bool `json:"horizons,omitempty"`

	// MarketId corresponds to the JSON schema field "marketId".
	MarketId int `json:"marketId"`

	// Modules corresponds to the JSON schema field "modules".
	Modules []string `json:"modules"`

	// StationName corresponds to the JSON schema field "stationName".
	StationName string `json:"stationName"`

	// SystemName corresponds to the JSON schema field "systemName".
	SystemName string `json:"systemName"`

	// Timestamp corresponds to the JSON schema field "timestamp".
	Timestamp string `json:"timestamp"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OutfittingV20JsonMessage) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["marketId"]; !ok || v == nil {
		return fmt.Errorf("field marketId: required")
	}
	if v, ok := raw["modules"]; !ok || v == nil {
		return fmt.Errorf("field modules: required")
	}
	if v, ok := raw["stationName"]; !ok || v == nil {
		return fmt.Errorf("field stationName: required")
	}
	if v, ok := raw["systemName"]; !ok || v == nil {
		return fmt.Errorf("field systemName: required")
	}
	if v, ok := raw["timestamp"]; !ok || v == nil {
		return fmt.Errorf("field timestamp: required")
	}
	type Plain OutfittingV20JsonMessage
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = OutfittingV20JsonMessage(plain)
	return nil
}

type OutfittingV20Json struct {
	// SchemaRef corresponds to the JSON schema field "$schemaRef".
	SchemaRef string `json:"$schemaRef"`

	// Header corresponds to the JSON schema field "header".
	Header OutfittingV20JsonHeader `json:"header"`

	// Message corresponds to the JSON schema field "message".
	Message OutfittingV20JsonMessage `json:"message"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OutfittingV20Json) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["$schemaRef"]; !ok || v == nil {
		return fmt.Errorf("field $schemaRef: required")
	}
	if v, ok := raw["header"]; !ok || v == nil {
		return fmt.Errorf("field header: required")
	}
	if v, ok := raw["message"]; !ok || v == nil {
		return fmt.Errorf("field message: required")
	}
	type Plain OutfittingV20Json
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = OutfittingV20Json(plain)
	return nil
}
